### PR TITLE
Added De-duplication logic for setup

### PR DESCRIPTION
**Pull request by Prannav-k**
@swapnilpawar31415 
Init method load logic
```
if contract_address is present
  if present in db
    load the params
  else
    set default params
    set newcontract to true
else
   create new sc address
   set default params      
   set newcontract to true

``` 

setup method de duplication logic
```
if not newcontract
 raise exception
```

### CODE REVIEW

**Comment by swapnilpawar31415** [comment]
shouldn't the else statement also have newcontract set as True?
else
   create new sc address
   set default params
   set newcontract to true

also we should initialize newcontract to False at the start? (just for clean code practice?)

**Comment by Prannav-k** [comment]
@swapnilpawar31415 yes, code is written like that. I the comment in here too. Thanks

**Comment by Prannav-k** [comment]
@swapnilpawar31415 added init new_contract logic too

**Review by swapnilpawar31415 — APPROVED** [review]
Looks fine to merge.

**Pull request merged**
